#!/usr/bin/env bash
#
# ArduPilot's OWN obstacle avoidance (BendyRuler), in the same Gazebo world the
# Nav2 stack flies. The comparison arm to ./start_sim.sh.
#
#   ./start_sim_oa.sh          start everything and attach
#   ./start_sim_oa.sh stop     kill the session and every sim process
#   ./start_sim_oa.sh status   show what is running
#
# Pane layout (tiled, one window):
#   0 gz sim   1 ArduPilot SITL   2 lidar->MAVLink bridge   3 mission   4 shell
#
# WHAT IS DIFFERENT FROM start_sim.sh
# There is no Nav2, no mavros, no costmaps, no TF and no RViz. The only ROS
# process is the ros_gz bridge that pulls /lidar/scan out of Gazebo, and
# mavlik_bridge.py, which turns that scan into MAVLink OBSTACLE_DISTANCE so
# ArduPilot can see the SAME buildings. Path planning happens inside the flight
# controller (OA_TYPE=1, BendyRuler) instead of on the companion.
#
# SEPARATE EEPROM -- THIS MATTERS FOR THE COMPARISON
# sim_vehicle.py persists parameters to eeprom.bin in its working directory. If
# this stack loaded oa.parm into the same directory the Nav2 stack uses, then
# OA_TYPE/PRX1_TYPE would still be set on the NEXT Nav2 run, and Nav2 would be
# flying on top of an ArduPilot avoidance layer without anyone noticing. So the
# OA vehicle runs out of $SITL_DIR with its own eeprom. Leave it that way.
#
# GZ_IP=127.0.0.1 is pinned for the same reason as start_sim.sh -- see the long
# comment there about gz-transport discovery picking a VPN interface.

set -uo pipefail

# ---------------- config ----------------
# Derived from this script's own location, so a clone under any directory
# name works. The repo clones as obstacle_avoidance_drone, which the old
# $HOME/obstacle_avoidance default did not match.
WS="${WS:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
SESSION="${SESSION:-simoa}"
ROS_SETUP="${ROS_SETUP:-/opt/ros/lyrical/setup.bash}"
RUN_DIR="${RUN_DIR:-/tmp/drone_sim_oa}"

export GZ_IP="${GZ_IP:-127.0.0.1}"

# Same world as the Nav2 stack. Changing this breaks the comparison.
WORLD="${WORLD:-$WS/worlds/lawnmower.sdf}"

ARDUPILOT="${ARDUPILOT:-$HOME/dev/ardupilot}"
AP_GAZEBO="${AP_GAZEBO:-$HOME/dev/ardupilot_gazebo}"
SITL_DIR="${SITL_DIR:-$WS/.sitl_oa}"

MAV_BRIDGE="${MAV_BRIDGE:-$HOME/mavlik_bridge.py}"
SCAN_TOPIC="${SCAN_TOPIC:-/lidar/scan}"

# --out ports:
#   14550  MAVProxy's own GCS link (sim_vehicle default)
#   14551  mavlik_bridge.py   -- OBSTACLE_DISTANCE in, what oa.parm expects
#   14556  auto_takeoff.py
#   14557  oa_lawnmower.py
# Each pymavlink client binds its own port; two on one port silently split the
# stream and each sees half the messages.
SITL_OUT="${SITL_OUT:---out=udp:127.0.0.1:14551 --out=udp:127.0.0.1:14556 --out=udp:127.0.0.1:14557}"

# gazebo-iris-gimbal.parm sets the frame/motor/gimbal config; oa.parm layers
# BendyRuler + proximity on top. Order matters, oa.parm must come last.
PARM_FRAME="${PARM_FRAME:-$AP_GAZEBO/config/gazebo-iris-gimbal.parm}"
# Tracked in this repo so the OA tuning travels with the stack; the copy in
# $AP_GAZEBO/config is the same file.
PARM_OA="${PARM_OA:-$WS/oa.parm}"
# Comparison-only overlay: matches WP_SPD to Nav2's 1 m/s and unclamps the
# proximity filter. Without it the vehicle flies the course at the 10 m/s
# default and hits the first building. See the file for the arithmetic.
PARM_CMP="${PARM_CMP:-$WS/oa_compare.parm}"

SITL_CMD="${SITL_CMD:-$ARDUPILOT/Tools/autotest/sim_vehicle.py -v ArduCopter -f JSON --model JSON --map --console --add-param-file=$PARM_FRAME --add-param-file=$PARM_OA --add-param-file=$PARM_CMP $SITL_OUT}"

AUTO_TAKEOFF="${AUTO_TAKEOFF:-1}"
TAKEOFF_ALT="${TAKEOFF_ALT:-10}"

CLOCK_BRIDGE='/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock'
SCAN_BRIDGE='/lidar/scan@sensor_msgs/msg/LaserScan[gz.msgs.LaserScan'

# Bracketed first char so the pattern never matches the pkill command line
# itself (which would kill this script / your ssh shell).
SIM_PATTERNS=(
  "[g]z sim" "[p]arameter_bridge" "[m]avlik_bridge.py"
  "[a]uto_takeoff.py" "[o]a_lawnmower.py"
)
SITL_PATTERNS=( "[s]im_vehicle.py" "[a]rducopter" "[m]avproxy" )

say()  { printf '\033[1;35m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }

# make_pane_script <index> <name> <cwd> <body...>
make_pane_script() {
  local idx="$1" name="$2" cwd="$3"; shift 3
  local f="$RUN_DIR/pane${idx}.sh"
  {
    echo '#!/usr/bin/env bash'
    echo "# pane $idx: $name (generated by start_sim_oa.sh)"
    echo "export GZ_IP=$GZ_IP"
    # ROS setup files read unset vars, so no `set -u` in here.
    echo "source $ROS_SETUP"
    echo "cd $cwd"
    echo "$*"
    echo 'rc=$?'
    echo 'echo; echo "--- pane exited (rc=$rc); shell follows ---"'
    echo 'exec bash'
  } > "$f"
  chmod +x "$f"
}

start_pane() { tmux respawn-pane -k -t "$SESSION:0.$1" "bash $RUN_DIR/pane${1}.sh"; }

kill_sim() {
  tmux kill-session -t "$SESSION" 2>/dev/null && say "killed tmux session '$SESSION'"
  local p
  for p in "${SIM_PATTERNS[@]}" "${SITL_PATTERNS[@]}"; do pkill -f "$p" 2>/dev/null; done
  sleep 2
  for p in "${SIM_PATTERNS[@]}" "${SITL_PATTERNS[@]}"; do pkill -9 -f "$p" 2>/dev/null; done
  pkill -9 -f "[x]term.*ArduCopter" 2>/dev/null

  # Fast DDS leaves shared-memory segments behind when a participant is
  # SIGKILLed, and they poison discovery once enough pile up. fuser tells us
  # which are still held by a live process, so only orphans go.
  local seg n=0
  for seg in /dev/shm/fastdds_* /dev/shm/fastrtps_* \
             /dev/shm/sem.fastdds_* /dev/shm/sem.fastrtps_*; do
    [[ -e "$seg" ]] || continue
    fuser -s "$seg" 2>/dev/null && continue
    rm -f "$seg" 2>/dev/null && n=$((n + 1))
  done
  [[ "$n" -gt 0 ]] && say "removed $n orphaned Fast DDS shm segments"

  say "sim processes cleared"
}

# ---------------- subcommands ----------------
case "${1:-start}" in
  stop)   kill_sim; exit 0 ;;
  status)
    tmux ls 2>/dev/null || echo "(no tmux sessions)"
    echo "--- sim processes ---"
    pgrep -af "gz sim|arducopter|parameter_bridge|mavlik_bridge" \
      | grep -v pgrep || echo "(none)"
    exit 0 ;;
  start) ;;
  *) echo "usage: $0 [start|stop|status]" >&2; exit 2 ;;
esac

# ---------------- preflight ----------------
[[ -f "$ROS_SETUP" ]] || { echo "no ROS setup at $ROS_SETUP" >&2; exit 1; }
for f in "$WORLD" "$PARM_FRAME" "$PARM_OA" "$PARM_CMP" "$MAV_BRIDGE" \
         "$WS/auto_takeoff.py" "$WS/oa_lawnmower.py" "$WS/pattern.py"; do
  [[ -f "$f" ]] || { echo "missing $f" >&2; exit 1; }
done

if tmux has-session -t "$SESSION" 2>/dev/null; then
  warn "session '$SESSION' already exists — tearing it down first"
fi
kill_sim
mkdir -p "$RUN_DIR" "$SITL_DIR"

# oa_lawnmower.py imports pattern.py, and mavlik_bridge.py lives in $HOME.
# Both panes run from $WS, so only the bridge needs its full path.

set +u
# shellcheck disable=SC1090
source "$ROS_SETUP"
set -u
ros2 daemon stop >/dev/null 2>&1

# ---------------- build the session ----------------
say "creating tmux session '$SESSION' (GZ_IP=$GZ_IP)"
tmux new-session -d -s "$SESSION" -n simoa -c "$WS"
for _ in 1 2 3 4; do
  tmux split-window -t "$SESSION:0" -c "$WS"
  tmux select-layout -t "$SESSION:0" tiled >/dev/null
done
tmux select-layout -t "$SESSION:0" tiled >/dev/null
tmux set-option -t "$SESSION" remain-on-exit on >/dev/null
tmux set-option -t "$SESSION" pane-border-status top >/dev/null
tmux set-option -t "$SESSION" mouse on >/dev/null

names=(gz sitl bridge mission shell)
for i in 0 1 2 3 4; do
  tmux select-pane -t "$SESSION:0.$i" -T " ${names[$i]} " >/dev/null
done

make_pane_script 0 gz     "$WS" "gz sim -v3 -r $WORLD"
make_pane_script 1 sitl   "$SITL_DIR" "$SITL_CMD"
# One pane runs both ROS pieces: the gz->ROS scan bridge, then the scan->MAVLink
# bridge. `&` backgrounds the parameter_bridge so both live in this pane.
make_pane_script 2 bridge "$WS" \
  "ros2 run ros_gz_bridge parameter_bridge $CLOCK_BRIDGE $SCAN_BRIDGE & sleep 3; python3 $MAV_BRIDGE --scan-topic $SCAN_TOPIC --mavlink udp:127.0.0.1:14551"

if [[ "$AUTO_TAKEOFF" == "1" ]]; then
  make_pane_script 3 mission "$WS" \
    "python3 $WS/auto_takeoff.py --alt $TAKEOFF_ALT --connection udpin:0.0.0.0:14556"
else
  make_pane_script 3 mission "$WS" \
    "echo 'AUTO_TAKEOFF=0. python3 auto_takeoff.py --connection udpin:0.0.0.0:14556'"
fi
make_pane_script 4 shell "$WS" "echo 'then: python3 oa_lawnmower.py'"

# ---------------- staged start ----------------
say "pane 0: gazebo"
start_pane 0

say "waiting for gz /clock to have a publisher"
for _ in $(seq 1 60); do
  if gz topic -i -t /clock 2>/dev/null | grep -q "Publishers"; then
    say "gz /clock is live"; break
  fi
  sleep 1
done

say "pane 1: ArduPilot SITL (eeprom in $SITL_DIR, oa.parm loaded)"
start_pane 1

say "pane 2: lidar -> OBSTACLE_DISTANCE bridge"
start_pane 2

# auto_takeoff blocks on EKF/GPS lock itself, so no gate needed here -- unlike
# the Nav2 stack there is no lifecycle bringup racing the clock.
say "pane 3: takeoff"
start_pane 3
start_pane 4

cat <<EOF

  ArduPilot OA stack up in tmux session '$SESSION'.

  Pane 3 climbs to ${TAKEOFF_ALT} m and stops. Then, in pane 4:

      python3 oa_lawnmower.py

  Same waypoints as the Nav2 run (pattern.py), same world. ArduPilot plans
  around obstacles itself; there is no Nav2 anywhere in this stack.

  Check avoidance is actually armed before trusting a run:
      in the SITL console (pane 1):  param show OA_TYPE     -> 1
                                     param show PRX1_TYPE   -> 2
      pane 2 should print a heartbeat and then stay quiet.
      MAVProxy map: obstacles show as ADSB targets (OA_DB_OUTPUT 3).

  attach:  tmux attach -t $SESSION
  stop:    $0 stop
  Nav2 arm of the comparison:  ./start_sim.sh   (session 'sim')

EOF

if [[ -t 0 && -t 1 ]]; then
  sleep 1
  tmux attach -t "$SESSION"
else
  say "not a tty — session left running; attach with: tmux attach -t $SESSION"
fi
