#!/usr/bin/env bash
#
# Bring up the whole SITL + Gazebo obstacle-avoidance sim in one tmux session.
#
#   ./start_sim.sh          start everything and attach
#   ./start_sim.sh stop     kill the session and every sim process
#   ./start_sim.sh status   show what is running
#
# Pane layout (tiled, one window):
#   0 gz sim   1 ArduPilot SITL   2 bringup   3 nav2   4 rviz   5 takeoff
#
# *** GZ_IP=127.0.0.1 is the whole reason this script exists. ***
# gz-transport picks ONE interface for its multicast discovery when a process
# starts. On this box `ip addr` shows lo, wlo1 (192.168.1.174), tailscale0
# (100.97.60.103) and docker0, and tailscale0 is a POINTOPOINT link that does
# not carry gz's discovery multicast. Start gz sim and ros_gz_bridge at
# different moments (e.g. tailscale comes up in between, as it does at boot)
# and they land on different interfaces: `gz topic -i -t /clock` then reports
# "No publishers" with only the bridge as a subscriber, so ROS /clock and
# /lidar/scan stay silent, every use_sim_time node has frozen time, the
# costmaps never publish, and RViz is completely empty while Gazebo itself
# looks perfectly healthy. Pinning every gz-transport process to loopback
# makes discovery deterministic and immune to VPN/interface churn.

set -uo pipefail

# ---------------- config ----------------
# Derived from this script's own location, so a clone under any directory
# name works. The repo clones as obstacle_avoidance_drone, which the old
# $HOME/obstacle_avoidance default did not match.
WS="${WS:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
SESSION="${SESSION:-sim}"
ROS_SETUP="${ROS_SETUP:-/opt/ros/lyrical/setup.bash}"
RUN_DIR="${RUN_DIR:-/tmp/drone_sim}"

export GZ_IP="${GZ_IP:-127.0.0.1}"

# Our own world, not the stock ardupilot_gazebo runway.sdf: same physics /
# lighting / spawn point, plus the lawnmower course buildings. Kept in-project
# so the ardupilot_gazebo checkout stays pristine. WORLD=runway.sdf still works
# (gz resolves that one off GZ_SIM_RESOURCE_PATH).
WORLD="${WORLD:-$WS/worlds/lawnmower.sdf}"
ARDUPILOT="${ARDUPILOT:-$HOME/dev/ardupilot}"
# --out ports: mavros owns 14550 (sim_vehicle hands that out by default). The
# two extra streams are for the pymavlink clients, which each need their own
# endpoint -- two processes reading the same UDP socket steal each other's
# packets, so sharing 14550 with mavros makes both flaky.
#   14555  cmd_vel_to_mavros.py  (send_ned velocity setpoints)
#   14556  auto_takeoff.py       (mode/arm/takeoff)
SITL_OUT="${SITL_OUT:---out=udp:127.0.0.1:14555 --out=udp:127.0.0.1:14556}"
SITL_CMD="${SITL_CMD:-$ARDUPILOT/Tools/autotest/sim_vehicle.py -v ArduCopter -f JSON --model JSON --map --console $SITL_OUT}"

# Pane 5 gets the drone airborne and hovering, then stops and hands you a
# shell -- goals are sent by hand (python3 send_nav_goal.py, or the RViz "Nav2
# Goal" tool). AUTO_TAKEOFF=0 leaves pane 5 as a plain shell instead.
AUTO_TAKEOFF="${AUTO_TAKEOFF:-1}"
TAKEOFF_ALT="${TAKEOFF_ALT:-10}"

BRINGUP_LAUNCH="$WS/src/obstacle_avoidance/launch/bringup.launch.py"
NAV2_LAUNCH="$WS/src/obstacle_avoidance/launch/nav2_mppi.launch.py"
RVIZ_CFG="$WS/src/obstacle_avoidance/config/nav2_drone.rviz"

# Bracketed first char so the pattern never matches the pkill command line
# itself (which would kill this script / your ssh shell).
SIM_PATTERNS=(
  "[g]z sim" "[r]viz2" "[p]arameter_bridge" "[m]avros_node" "[t]f_publisher"
  "[c]md_vel_to_mavros" "[a]uto_takeoff.py" "[s]end_nav_goal.py"
  "[l]awnmower.py"
  "[c]ontroller_server" "[p]lanner_server"
  "[b]ehavior_server" "[b]t_navigator" "[w]aypoint_follower"
  "[l]ifecycle_manager"
)
SITL_PATTERNS=( "[s]im_vehicle.py" "[a]rducopter" "[m]avproxy" )

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }

# make_pane_script <index> <name> <body...>
# The body runs, then an interactive shell takes over, so a crashed node leaves
# its error on screen with a usable prompt under it.
make_pane_script() {
  local idx="$1" name="$2"; shift 2
  local f="$RUN_DIR/pane${idx}.sh"
  {
    echo '#!/usr/bin/env bash'
    echo "# pane $idx: $name (generated by start_sim.sh)"
    echo "export GZ_IP=$GZ_IP"
    
    # ROS setup files read unset vars, so no `set -u` in here.
    echo "source $ROS_SETUP"
    echo "source $WS/install/setup.bash"
    echo "cd $WS"
    echo "$*"
    echo 'rc=$?'
    echo 'echo; echo "--- pane exited (rc=$rc); shell follows ---"'
    echo 'exec bash'
  } > "$f"
  chmod +x "$f"
}

start_pane() { tmux respawn-pane -k -t "$SESSION:0.$1" "bash $RUN_DIR/pane${1}.sh"; }

kill_sim() {
  tmux kill-session -t "$SESSION" 2>/dev/null && say "killed tmux session '$SESSION'"
  local p
  for p in "${SIM_PATTERNS[@]}" "${SITL_PATTERNS[@]}"; do pkill -f "$p" 2>/dev/null; done
  sleep 2
  for p in "${SIM_PATTERNS[@]}" "${SITL_PATTERNS[@]}"; do pkill -9 -f "$p" 2>/dev/null; done
  pkill -9 -f "[x]term.*ArduCopter" 2>/dev/null

  # Fast DDS leaves its shared-memory segments behind when a participant is
  # SIGKILLed, which is exactly what we just did to a dozen of them. They
  # accumulate across runs (94 of them after an afternoon of restarts) and
  # eventually poison discovery: nodes come up fine and `ros2 lifecycle get`
  # answers, but lifecycle_manager sits forever on "Waiting for service
  # controller_server/get_state..." because its client never matches. Nothing
  # of ours is running at this point, so the whole set is garbage.
  # fuser tells us which segments a live participant still has open (the ros2
  # CLI daemon keeps its own), so only the orphans get removed -- no guessing
  # about what else on the box might be using DDS.
  local seg n=0
  for seg in /dev/shm/fastdds_* /dev/shm/fastrtps_* \
             /dev/shm/sem.fastdds_* /dev/shm/sem.fastrtps_*; do
    [[ -e "$seg" ]] || continue
    fuser -s "$seg" 2>/dev/null && continue
    rm -f "$seg" 2>/dev/null && n=$((n + 1))
  done
  [[ "$n" -gt 0 ]] && say "removed $n orphaned Fast DDS shm segments"

  say "sim processes cleared"
}

# ---------------- subcommands ----------------
case "${1:-start}" in
  stop)   kill_sim; exit 0 ;;
  status)
    tmux ls 2>/dev/null || echo "(no tmux sessions)"
    echo "--- sim processes ---"
    pgrep -af "gz sim|arducopter|mavros_node|parameter_bridge|bt_navigator|rviz2" \
      | grep -v pgrep || echo "(none)"
    exit 0 ;;
  start) ;;
  *) echo "usage: $0 [start|stop|status]" >&2; exit 2 ;;
esac

# ---------------- preflight ----------------
[[ -f "$ROS_SETUP" ]] || { echo "no ROS setup at $ROS_SETUP" >&2; exit 1; }
[[ -f "$WS/install/setup.bash" ]] || {
  echo "workspace not built: $WS/install/setup.bash missing (run colcon build)" >&2
  exit 1; }
for f in "$BRINGUP_LAUNCH" "$NAV2_LAUNCH" "$RVIZ_CFG" \
         "$WS/auto_takeoff.py" "$WS/send_nav_goal.py" "$WS/lawnmower.py"; do
  [[ -f "$f" ]] || { echo "missing $f" >&2; exit 1; }
done

if tmux has-session -t "$SESSION" 2>/dev/null; then
  warn "session '$SESSION' already exists — tearing it down first"
fi
kill_sim
mkdir -p "$RUN_DIR"

set +u
# shellcheck disable=SC1090
source "$ROS_SETUP"
# shellcheck disable=SC1091
source "$WS/install/setup.bash"
set -u

# The ros2 CLI daemon caches a stale node/action graph across runs and will
# happily report nodes from the run you just killed. Drop it.
ros2 daemon stop >/dev/null 2>&1

# ---------------- build the session ----------------
say "creating tmux session '$SESSION' (GZ_IP=$GZ_IP)"
tmux new-session -d -s "$SESSION" -n sim -c "$WS"
for _ in 1 2 3 4 5; do
  tmux split-window -t "$SESSION:0" -c "$WS"
  tmux select-layout -t "$SESSION:0" tiled >/dev/null
done
tmux select-layout -t "$SESSION:0" tiled >/dev/null
tmux set-option -t "$SESSION" remain-on-exit on >/dev/null
tmux set-option -t "$SESSION" pane-border-status top >/dev/null
tmux set-option -t "$SESSION" mouse on >/dev/null

names=(gz sitl bringup nav2 rviz takeoff)
for i in 0 1 2 3 4 5; do
  tmux select-pane -t "$SESSION:0.$i" -T " ${names[$i]} " >/dev/null
done

make_pane_script 0 gz    "gz sim -v3 -r $WORLD"
make_pane_script 1 sitl  "$SITL_CMD"
make_pane_script 2 bringup "ros2 launch $BRINGUP_LAUNCH"
make_pane_script 3 nav2  "ros2 launch $NAV2_LAUNCH"
make_pane_script 4 rviz  "rviz2 -d $RVIZ_CFG"
# Pane 5: GUIDED + arm + takeoff, then an interactive shell (make_pane_script
# always execs bash afterwards) so you can send goals yourself. Started further
# down, once nav2 has actually reached ACTIVE.
if [[ "$AUTO_TAKEOFF" == "1" ]]; then
  make_pane_script 5 takeoff "python3 $WS/auto_takeoff.py --alt $TAKEOFF_ALT"
else
  make_pane_script 5 shell \
    "echo 'AUTO_TAKEOFF=0. Fly it by hand: python3 auto_takeoff.py, then python3 send_nav_goal.py'"
fi

# ---------------- staged start ----------------
# Order matters here, unlike the hardware stack: gz must be publishing /clock
# before anything with use_sim_time comes up, or Nav2's lifecycle bringup races
# a frozen clock and aborts.
say "pane 0: gazebo"
start_pane 0

say "waiting for gz /clock to have a publisher"
for _ in $(seq 1 60); do
  if gz topic -i -t /clock 2>/dev/null | grep -q "Publishers"; then
    say "gz /clock is live"; break
  fi
  sleep 1
done
gz topic -i -t /clock 2>/dev/null | grep -q "Publishers" \
  || warn "gz /clock still has no publisher — check pane 0"

say "pane 1: ArduPilot SITL"
start_pane 1

say "pane 2: bringup (clock+scan bridges, mavros, tf)"
start_pane 2

say "waiting for ROS /clock to tick"
for _ in $(seq 1 40); do
  if timeout 3 ros2 topic echo /clock --once >/dev/null 2>&1; then
    say "ROS /clock is ticking"; break
  fi
  sleep 1
done

# Nav2's activate transition blocks in the costmaps until map->base_link is
# available, and that transform only appears once mavros publishes
# /mavros/local_position/pose -- i.e. after ArduPilot's EKF has GPS lock, which
# takes ~60 s from a cold SITL start. Starting nav2 before that means the
# lifecycle manager sits in activate until it gives up and aborts bringup.
# NB: no pipeline here. `set -o pipefail` is on above, and `... | grep -q`
# makes grep exit on its first match, which SIGPIPEs tf2_echo and leaves the
# pipeline status non-zero even on success -- the gate would never open.
have_map_tf() {
  local out
  out="$(timeout 5 ros2 run tf2_ros tf2_echo map base_link 2>&1 || true)"
  [[ "$out" == *Translation* ]]
}
say "waiting for map->base_link (EKF/GPS lock)"
for _ in $(seq 1 90); do
  if have_map_tf; then
    # Don't start nav2 the instant the transform first appears. mavros'
    # pose stream is still settling then, and controller_server's activate
    # can abort on a gap. A few seconds of margin removed that race.
    say "map->base_link is available (letting the pose stream settle)"
    sleep 5
    break
  fi
  sleep 1
done
have_map_tf \
  || warn "map->base_link still missing - nav2 activation will abort (check pane 2/mavros)"

# Nav2's lifecycle bringup is racy on a box this busy: gz, SITL, mavros and
# rviz are all fighting for CPU while lifecycle_manager walks five servers
# through configure+activate, and a dropped change_state response strands the
# whole chain half-configured ("failed to send response to
# /behavior_server/change_state ... client will not receive response"). The
# manager does not retry, so bt_navigator simply never appears and the mission
# pane waits forever on an action server that is never coming. Poll for
# bt_navigator actually reaching ACTIVE and respawn the pane if it doesn't.
nav2_active() {
  local out
  out="$(timeout 8 ros2 lifecycle get /bt_navigator 2>/dev/null || true)"
  [[ "$out" == active* ]]
}

NAV2_WAIT="${NAV2_WAIT:-150}"   # seconds to allow per attempt
nav2_up=0
for attempt in 1 2 3; do
  say "pane 3: nav2 (attempt $attempt)"
  start_pane 3
  # Wall-clock deadline, not an iteration count: each nav2_active call can
  # itself burn up to its own timeout, so counting loops would drift.
  deadline=$(( SECONDS + NAV2_WAIT ))
  while (( SECONDS < deadline )); do
    if nav2_active; then nav2_up=1; break; fi
    sleep 2
  done
  [[ "$nav2_up" == 1 ]] && { say "nav2 is active"; break; }
  warn "nav2 did not reach active within ${NAV2_WAIT}s — restarting pane 3"
done
[[ "$nav2_up" == 1 ]] || warn "nav2 never activated; check pane 3"

# rviz last: it is the heaviest process here and only cosmetic, so keeping it
# out of the way until nav2 has settled removes one source of the race above.
say "pane 4: rviz"
start_pane 4

# Pane 5 only now, so the shell it drops you into is one you can send a goal
# from immediately rather than one racing nav2's bringup.
say "pane 5: takeoff"
start_pane 5

cat <<EOF

  Sim starting in tmux session '$SESSION'.

  Pane 5 (takeoff) waits for EKF/GPS lock, switches to GUIDED, arms and climbs
  to ${TAKEOFF_ALT} m, then leaves you a shell there. Send goals yourself:

      python3 lawnmower.py                 # the full survey pattern
      python3 send_nav_goal.py 0 45        # or one goal: x=east, y=north
      python3 send_nav_goal.py --cancel
      # or the RViz "Nav2 Goal" button

  lawnmower.py flies 10 corners of a boustrophedon survey. Two of them are
  blocked on purpose by buildings in worlds/lawnmower.sdf -- (-15, 45) is
  buried inside one, (15, 5) is walled inside a courtyard -- and both should
  come out SKIPPED while the mission carries on. Preview the pattern without
  flying:  python3 lawnmower.py --dry-run

  Keep goals inside the global costmap, which spans +/-50 m from takeoff.

  Other knobs:  TAKEOFF_ALT=15 $0      AUTO_TAKEOFF=0 $0   (no auto takeoff)

  attach:  tmux attach -t $SESSION
  panes:   Ctrl-b <arrow>   zoom: Ctrl-b z   detach: Ctrl-b d
  stop:    $0 stop
  scripts: $RUN_DIR/pane*.sh

EOF

if [[ -t 0 && -t 1 ]]; then
  sleep 1
  tmux attach -t "$SESSION"
else
  say "not a tty — session left running; attach with: tmux attach -t $SESSION"
fi
