#!/usr/bin/env bash
#
# Bring up the whole obstacle-avoidance stack in one tmux session.
#
#   ./start_stack.sh          start everything and attach
#   ./start_stack.sh stop     kill the session and every stack process
#   ./start_stack.sh status   show what is running
#   ./start_stack.sh dry-run  build the panes but only print the commands
#
# Pane layout (tiled, one window):
#   0 mavproxy   1 bringup_hw   2 nav2_hw
#   3 goal_socket_bridge   4 status dashboard   5 send_goal shell
#
# Everything starts AT ONCE and the session attaches immediately, so you watch
# each pane come up in its own pane instead of staring at a progress line. No
# staged waits: nothing here actually requires them. goal_socket_bridge checks
# the Nav2 action server at goal-send time (not at startup), and Nav2 tolerates
# TF/pose arriving late. Pane 4 polls live readiness and tells you when a goal
# would actually be accepted -- that is the thing worth watching.
#
# Each pane runs a generated script from $RUN_DIR via `tmux respawn-pane`, NOT
# `send-keys`. send-keys types characters at a pane's shell and depends on that
# shell being ready to read them -- panes fed later in the sequence silently
# dropped their commands and sat at a prompt while the script reported success.
# respawn-pane replaces the pane's process outright, so a pane either runs its
# script or is visibly dead. It also skips ~/.bashrc (which sources a
# nonexistent /opt/ros/jazzy/setup.bash and prints an error on every new shell).
#
# The drone still has to be armed and airborne in GUIDED before a goal does
# anything -- cmdvel_to_send_ned emits SET_POSITION_TARGET_LOCAL_NED, which
# ArduCopter ignores otherwise. Do that in the mavproxy pane (pane 0).

set -uo pipefail

# ---------------- config ----------------
WS="${WS:-$HOME/obstacle_avoidance_drone}"
SESSION="${SESSION:-drone}"
ROS_SETUP="${ROS_SETUP:-/opt/ros/humble/setup.bash}"
RUN_DIR="${RUN_DIR:-/tmp/drone_stack}"

# MAVProxy fans the link out over the local network only — no serial here.
# 14550 -> MAVROS, 14551 -> cmdvel_to_send_ned, 14552 -> spare (GCS/QGC).
MAVPROXY_CMD="${MAVPROXY_CMD:-mavproxy.py --out udp:0.0.0.0:14550 --out udp:0.0.0.0:14551 --out udp:0.0.0.0:14552}"

BRINGUP_LAUNCH="$WS/src/obstacle_avoidance_hw/launch/bringup_hw.launch.py"
NAV2_LAUNCH="$WS/src/obstacle_avoidance_hw/launch/nav2_hw.launch.py"
MONITOR_PY="$WS/stack_monitor.py"

# Processes to sweep on stop. Bracketed first char so the pattern never matches
# the pkill command line itself (which would kill this script / your ssh shell).
STACK_PATTERNS=(
  "[b]ringup_hw" "[n]av2_hw" "[s]f45b" "[m]avros_node" "[t]f_publisher"
  "[g]oal_socket_bridge" "[c]mdvel_to_send_ned" "[c]ontroller_server"
  "[p]lanner_server" "[b]ehavior_server" "[b]t_navigator"
  "[w]aypoint_follower" "[l]ifecycle_manager" "[s]tack_monitor"
)

# ---------------- helpers ----------------
say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }

# make_pane_script <index> <name> <body...>
# Writes $RUN_DIR/paneN.sh. The body runs, then an interactive shell takes over
# so a crashed node leaves you a usable prompt in place with its error above.
make_pane_script() {
  local idx="$1" name="$2"; shift 2
  local f="$RUN_DIR/pane${idx}.sh"
  {
    echo '#!/usr/bin/env bash'
    echo "# pane $idx: $name (generated by start_stack.sh)"
    if (( DRY )); then
      echo "echo '[dry-run] would run:'"
      printf 'echo %q\n' "$*"
    else
      # ROS setup files read unset vars, so no `set -u` here.
      echo "source $ROS_SETUP"
      echo "source $WS/install/setup.bash"
      echo "$*"
      echo 'rc=$?'
      echo 'echo; echo "--- pane exited (rc=$rc); shell follows ---"'
    fi
    echo 'exec bash'
  } > "$f"
  chmod +x "$f"
}

start_pane() { tmux respawn-pane -k -t "$SESSION:0.$1" "bash $RUN_DIR/pane${1}.sh"; }

kill_stack() {
  tmux kill-session -t "$SESSION" 2>/dev/null && say "killed tmux session '$SESSION'"
  local p
  for p in "${STACK_PATTERNS[@]}"; do pkill -f "$p" 2>/dev/null; done
  sleep 2
  for p in "${STACK_PATTERNS[@]}"; do pkill -9 -f "$p" 2>/dev/null; done
  say "stack processes cleared (mavproxy left alone)"
}

# ---------------- subcommands ----------------
DRY=0
case "${1:-start}" in
  stop)
    kill_stack
    exit 0
    ;;
  status)
    tmux ls 2>/dev/null || echo "(no tmux sessions)"
    echo "--- stack processes ---"
    pgrep -af "sf45b|mavros_node|goal_socket|bt_navigator|controller_server|mavproxy" \
      | grep -v pgrep || echo "(none)"
    exit 0
    ;;
  start) ;;
  dry-run|--dry-run) DRY=1; SESSION="${SESSION}-dry"; RUN_DIR="${RUN_DIR}-dry" ;;
  *) echo "usage: $0 [start|stop|status|dry-run]" >&2; exit 2 ;;
esac

# ---------------- preflight ----------------
[[ -f "$ROS_SETUP" ]] || { echo "no ROS setup at $ROS_SETUP" >&2; exit 1; }
[[ -f "$WS/install/setup.bash" ]] || {
  echo "workspace not built: $WS/install/setup.bash missing (run colcon build)" >&2
  exit 1; }
[[ -f "$BRINGUP_LAUNCH" ]] || { echo "missing $BRINGUP_LAUNCH" >&2; exit 1; }
[[ -f "$NAV2_LAUNCH" ]] || { echo "missing $NAV2_LAUNCH" >&2; exit 1; }
[[ -f "$MONITOR_PY" ]] || { echo "missing $MONITOR_PY" >&2; exit 1; }

if [[ ! -e /dev/ttyACM0 ]]; then
  warn "/dev/ttyACM0 not present — the SF45 lidar is not plugged in; bringup will fail"
fi

if tmux has-session -t "$SESSION" 2>/dev/null; then
  warn "session '$SESSION' already exists — tearing it down first"
  kill_stack
fi

mkdir -p "$RUN_DIR"

# ROS in this shell too, so `ros2 daemon stop` below works.
# ROS's setup.bash reads unset vars (AMENT_TRACE_SETUP_FILES et al), so drop
# `set -u` across the sourcing or it aborts here.
set +u
# shellcheck disable=SC1090
source "$ROS_SETUP"
# shellcheck disable=SC1091
source "$WS/install/setup.bash"
set -u

# The ros2 CLI daemon caches the node/action graph and happily reports nodes
# from a PREVIOUS run that are long dead — that false positive made an earlier
# version of this script declare Nav2 ready 3s in while its pane sat at a
# prompt. Kill it so any `ros2 topic/node list` you run by hand is truthful.
# (The status pane is a real ROS node and never consults the daemon.)
if (( ! DRY )); then
  ros2 daemon stop >/dev/null 2>&1
fi

# ---------------- build the session ----------------
say "creating tmux session '$SESSION'"
tmux new-session -d -s "$SESSION" -n stack -c "$WS"
for _ in 1 2 3 4 5; do
  tmux split-window -t "$SESSION:0" -c "$WS"
  tmux select-layout -t "$SESSION:0" tiled >/dev/null
done
tmux select-layout -t "$SESSION:0" tiled >/dev/null

# Keep dead panes visible instead of vanishing — a crash leaves its error on screen.
tmux set-option -t "$SESSION" remain-on-exit on >/dev/null
tmux set-option -t "$SESSION" pane-border-status top >/dev/null
tmux set-option -t "$SESSION" mouse on >/dev/null

names=(mavproxy bringup nav2 goal-bridge status send-goal)
for i in 0 1 2 3 4 5; do
  tmux select-pane -t "$SESSION:0.$i" -T " ${names[$i]} " >/dev/null
done

# ---------------- generate pane scripts ----------------
make_pane_script 0 mavproxy "$MAVPROXY_CMD"
make_pane_script 1 bringup "ros2 launch $BRINGUP_LAUNCH"
make_pane_script 2 nav2 "ros2 launch $NAV2_LAUNCH"
make_pane_script 3 goal-bridge "ros2 run obstacle_avoidance_hw goal_socket_bridge"
make_pane_script 4 status "python3 $MONITOR_PY"
make_pane_script 5 send-goal \
  "cd $WS; echo 'Arm + takeoff in pane 0, watch pane 4, then:  python3 send_goal.py'"

# ---------------- start everything at once ----------------
say "starting all 6 panes"
for i in 0 1 2 3 4 5; do start_pane "$i"; done

cat <<EOF

  Stack starting in tmux session '$SESSION' — watch the panes.

  Pane 4 (status) shows what is up and what is still missing.
  When it reads GOAL READY: YES, in the mavproxy pane (0):
      mode guided
      arm throttle
      takeoff 10
  then in pane 5:
      python3 send_goal.py

  attach:  tmux attach -t $SESSION
  panes:   Ctrl-b <arrow>    zoom: Ctrl-b z    detach: Ctrl-b d
  stop:    $0 stop
  scripts: $RUN_DIR/pane*.sh

EOF

if [[ -t 0 && -t 1 ]]; then
  sleep 1
  tmux attach -t "$SESSION"
else
  say "not a tty — session left running; attach with: tmux attach -t $SESSION"
fi
